### PR TITLE
Caddy usage - htpasswd file isn't reloaded (on insert, on update or on delete)

### PR DESCRIPTION
**Pull request by magikstm**
It doesn't use a `sync.RwMutex` as I was unsure if it was required with my current implementation.

I also didn't add a test yet.

It solves the issue I mentioned in #20. It may need a bit more work though.

Please review this pull request.

### CODE REVIEW

**Comment by smancke** [comment]
@magikstm The PR looks good to me, but the locking by the RWMutex must be, because the user map may be changed while it's been accessed by reading operations.
And of course we need a test before merging.

**Comment by magikstm** [comment]
Thanks. I'm not that experienced in Golang and the sync and mutex concept are different to what I'm used to in other languages.

I tried adding an RWMutex to it. Please review it and confirm if this implementation could work.

**Comment by smancke** [comment]
Looks good.
Two styling things:
- the mutext variable should be a member variable of the auth struct
- Golang has this cool `defer` statement which guaranties the execution ant the end of a function (a bit like finally in C#). With this you could write 
```
mu.Lock()
defer mu.Unlock()
// code which should be synchronized
```

**Comment by magikstm** [comment]
Thanks. I read about "defer" a bit, but was unsure how to apply it.

I retested with my last commit and it seems to work properly now.

**Pull request merged**
