### PR TITLE
Caddy - Use {user} placeholder for logs #32

### PR DESCRIPTION
**Pull request by magikstm**
I tested it on Windows 7 x64 and it works.

I've not added tests yet.

@smancke please review it. I'm unsure if it is the best way to add this feature.

### CODE REVIEW

**Comment by smancke** [comment]
Hi @magikstm,
just looked at it and not tested it.
Is it working this way? For me it looks as the replacer is created, but not used anywhere ..

**Comment by smancke** [comment]
Oh, my answer was to fast .. I looked into it and now understand, why it works.
Maybe we should have a comment here, that the Constructor NewReplacer is not only creating a replacer, but also exchanging it into the supplied request context.

So, that it looks good to me. Would be cool, if you also could provide a test for this although I don't have an idea on how to test this. Do you have one?

**Comment by magikstm** [comment]
@smancke I'll try to write tests for handler.go, but I'm unsure I'll be able to. I'll update in 1-2 days.

**Comment by magikstm** [comment]
@smancke I added two tests for handler.go.

I'm still looking how to set a token to test the last lines.

**Comment by magikstm** [comment]
@smancke  My last commits test all lines and validate that token cookie is valid.

I don't know how to simply test the change made by these lines though:
> repl := httpserver.NewReplacer(r, nil, "-")
> repl.Set("user", userInfo.Sub)

@kujenga, @mholt or @tobya could you please review these:
https://github.com/magikstm/loginsrv/blob/master/caddy/handler.go#L31
https://github.com/magikstm/loginsrv/blob/master/caddy/handler_test.go#L62

I found this which I've reviewed a bit, but I don't think it applies to my test-case and I don't fully understand the use of `rr` and the second `p.ServeHTTP(rr, r)`:
https://github.com/mholt/caddy/blob/master/caddyhttp/proxy/proxy_test.go#L160

**Comment by mholt** [comment]
The responseRecorder (rr) is used to record the response and ensure that the placeholder value is in fact replaced. If so, it was set correctly. Looks pretty close to what you'd want to be doing. Hope that helps.

**Comment by magikstm** [comment]
@mholt thanks for the info.

I tried verifying the value of {user} with the `httpserver.NewReplacer` and I couldn't get the expected value. It does work outside tests locally for me in my log file. I may not be using the `NewResponseRecorder (rr)` correctly. I could try to add these eventually by reviewing how others do it in their plugin.

@smancke please review this PR. Feel free to edit as you wish and to try to add validations in tests to test the `{user}` change.

**Comment by magikstm** [comment]
Btw, when I run tests in Windows I get this failure:

> C:\go_projects\loginsrv>go test ./...
> ok      _/C_/go_projects/loginsrv       1.126s
> time="2017-11-09T21:44:31-05:00" level=warning msg="DEPRECATED: '-backend' is no longer supported. Please set the backends by explicit parameters"
> time="2017-11-09T21:44:31-05:00" level=warning msg="DEPRECATED: Please set the login path by parameter login_path and not as directive argument (Testfile:4)"
> time="2017-11-09T21:44:31-05:00" level=warning msg="DEPRECATED: '-backend' is no longer supported. Please set the backends by explicit parameters"
> time="2017-11-09T21:44:31-05:00" level=warning msg="DEPRECATED: Please set the login path by parameter login_path and not as directive argument (Testfile:4)"
> time="2017-11-09T21:44:31-05:00" level=warning msg="DEPRECATED: '-backend' is no longer supported. Please set the backends by explicit parameters"
> time="2017-11-09T21:44:31-05:00" level=warning msg="DEPRECATED: '-backend' is no longer supported. Please set the backends by explicit parameters"
> --- FAIL: TestSetup_RelativeTemplateFile (0.00s)
>         Error Trace:    setup_test.go:194
>         Error:          Not equal:
>                         expected: "C:\\Users\\Magik\\AppData\\Local\\Temp\\539635411/myTemplate.tpl"
>                         actual: "C:\\Users\\Magik\\AppData\\Local\\Temp\\539635411\\myTemplate.tpl"
> FAIL
> FAIL    _/C_/go_projects/loginsrv/caddy 0.068s
> ?       _/C_/go_projects/loginsrv/caddy/demo    [no test files]
> ok      _/C_/go_projects/loginsrv/htpasswd      2.108s
> ok      _/C_/go_projects/loginsrv/httpupstream  1.085s
> ok      _/C_/go_projects/loginsrv/logging       0.070s
> ok      _/C_/go_projects/loginsrv/login 0.083s
> ok      _/C_/go_projects/loginsrv/model 0.045s
> ok      _/C_/go_projects/loginsrv/oauth2        0.061s
> ok      _/C_/go_projects/loginsrv/osiam 1.064s

I can correct it by changing this line:
https://github.com/tarent/loginsrv/blob/master/caddy/setup_test.go#L179

To:
`expectedPath := root + "\\myTemplate.tpl"`

Or that second method:
1) Add this line in imports `"path/filepath"`
2) Change the line to: `expectedPath := filepath.FromSlash(root + "/myTemplate.tpl")`

I think the second method is required to allow a correct cross-platform filepath.

Ref: https://stackoverflow.com/questions/9371031/how-do-i-create-crossplatform-file-paths-in-go

**Comment by smancke** [comment]
Thanks, I try to look into it at the weekend!

**Comment by lhopki01** [comment]
This would be very useful.

**Comment by smancke** [comment]
I have added a check into the tests and merged it. 

@magikstm nice contribution!
IMO it would also make sense to change the Caddy default log format to have the user placeholder by default, since it is usually part of the common log format: https://github.com/mholt/caddy/blob/master/caddyhttp/log/log.go#L94

**Comment by magikstm** [comment]
Thanks @smancke. The additional validation to the test is excellent.

I created this issue in Caddy that is related to the default log format:
https://github.com/mholt/caddy/issues/1951

**Pull request merged**
