### PR TITLE
Remove a few useless lines and close file to avoid leaks

### PR DESCRIPTION
**Pull request by magikstm**
I believe these lines aren't useful.

### CODE REVIEW

**Comment by smancke** [comment]
I think, these lines are to totally useless: This ist the only place where the old modification time ist set.
The variable `modTime` seems useless to me.

**Comment by magikstm** [comment]
@smancke I added them in this commit (https://github.com/tarent/loginsrv/commit/d755aa8d43e4be20240dd67d56126990dfedbff7#diff-0f4283ef2130228d2a3c42d7f84dd4a6) and the solution has been enhanced since then and it may not have been perfect at that time.

I tested the related features that use the function "reloadIfChanged" for Htpasswd and I didn't notice a regression after the removal of those lines.

I think they could be removed safely.

**Comment by smancke** [comment]
@magikstm The lines were indeed useless, but this was a bug.
Now, I've rewritten the parts in https://github.com/tarent/loginsrv/commit/8e70a3a3333be1c03f6a83c51fd0d52bb8561f93  and changed the tests, to also check that the correct update timestamp is set.

**Comment by magikstm** [comment]
@smancke Awesome. Thanks a lot.

**Pull request closed without merging**
