### PR TITLE
Add new provider - SAML via Azure AD

### PR DESCRIPTION
**Pull request by greenpau**
Resolves: #168

### CODE REVIEW

**Comment by greenpau** [comment]
@smancke , qq, I create a doc for SAML provider [here](https://github.com/greenpau/loginsrv/tree/samlprovider#saml).

Should I put SAML provider documentation in a separate file or should I keep it in the main `README.md`?

I am documenting the work first, then I will put the necessary code together.

**Comment by g-w** [comment]
Hello @greenpau, 

thank you for your contribution!

For now simply put the documentation in the README.md.

**Comment by greenpau** [comment]
@g-w , could you please review the addition. I know that the coverage is not there. I would like to get general agreement on the proposal. Once finalized, I will improve the coverage.

**Comment by greenpau** [comment]
@g-w , any feedback?

**Comment by g-w** [comment]
Hello @greenpau, 

sorry for the delays, but since we are currently not using azure and i am not familiar with it, hence reviewien the changes is a bigger task. I will come back to in the next days.

**Comment by greenpau** [comment]
moved it to a new caddy v2 module https://github.com/greenpau/caddy-auth-forms

**Pull request closed without merging**
