### PR TITLE
Implement simple jwt refreshing

### PR DESCRIPTION
**Pull request by domano**

### CODE REVIEW

**Comment by smancke** [comment]
@domano The first fast look over it is fine.
Some suggestions:
- The token refresh count should be stored in the JWT and increased by 1 on every refresh. To limit the refresh, a max refresh count option should be configurable, which is 0 by default. So by default no refresh is allowed.
- Since the most users are using the token as cookie, the token refresh should also be able to take the existing cookie and update it. Eg. with POST and content-type != JWT, the token could be taken from the cookie. (But let's thing a bit, if this is a nice api design)

**Comment by domano** [comment]
Thanks for reviewing!

1. Ok, i'll add the counter
2. Let's talk about this on monday then.

**Comment by Kernle32DLL** [comment]
@smancke @domano Regarding the refresh limit - how would one configure unlimited refreshs? Just using an arbitrary big number seems lame. How about "-1" to signal unlimited refreshs?

**Comment by smancke** [comment]
> @smancke @domano Regarding the refresh limit - how would one configure unlimited refreshs? Just using an arbitrary big number seems lame. How about "-1" to signal unlimited refreshs?

@Kernle32DLL not sure, if we should support such an insecure configuration

**Comment by Kernle32DLL** [comment]
@smancke I just see the scenario that - if the refresh limit is not high enough - it could happen that you are suddenly logged out because the token cannot be refreshed any more. This is not transparent to the user, whom might suddenly get the login form again - without any reason why.

As for security - I don't think its that unsecure, because a reasonable token expire time will eventually put an end to endless refreshes (it will expire somewhen after the last refresh, that is when the user left the application).

**Comment by smancke** [comment]
@Kernle32DLL 
With an unlimited refresh count, you can continue a login for ever. With this, there is no way do disable a user or to force a change in users rights any more.

**Comment by Kernle32DLL** [comment]
@smancke good point. Still - not ideal. A long-term solution would be to invalidate issued tokens after said user changes. Alas make the service aware of some kind of "revocation list". However, I don't see this happening here, as this service does not (and should not) persist any issued token.

**Comment by smancke** [comment]
LGTM,
now only an addition to the README is missing

**Comment by domano** [comment]
README is updated. If everything is allright now i would be happy about a merge :)

**Comment by smancke** [comment]
OK, now it looks good to me,
@domano feel free to merge ..

**Pull request merged**
