### PR TITLE
Remove undocumented "files" parameter for htpasswd and enhance doc

### PR DESCRIPTION
**Pull request by magikstm**
This is a fix for #39.

It removes an undocumented parameter and enhances the doc in the main page on a related feature.

### CODE REVIEW

**Comment by smancke** [comment]
@vschmi Are you fine with this, or do you still use this 'files' parameter?

**Comment by smancke** [comment]
@domano 
Can you please check, if you are still using the `files` parameter in your config, or if we can remove it?

**Comment by domano** [comment]
I will look at it next week and update the PR. Sorry, i've just seen the PR

**Comment by magikstm** [comment]
I suggest merging this PR and closing the related issue.

It'll document a feature and anyone using the undocumented one that disappears will be able to use that one instead.

**Comment by magikstm** [comment]
I suggest reviewing this PR again and possibly merging it to enhance the documentation.

**Comment by g-w** [comment]
I will merge this PR. Since there was no objections against merging it.

**Pull request merged**
